language: scala
before-script:
  - git clone https://github.com/scalareflect/interpreter.git
  - git clone https://github.com/scalamacros/resetallattrs.git
  - cd interpreter
  - sbt publish-local
  - cd ..
  - cd resetallattrs
  - sbt publish-local
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package
scala:
  - 2.11.0
  - 2.11.1
  - 2.11.2
jdk:
  - oraclejdk7
notifications:
  email:
    - gvojin@gmail.com
branches:
  only:
    - master
